package_name: nefer
genshin_id: 10000122 # TODO: Check this
key: nefer
skill_data_mapping:
  attack:
    attack_1:
      - 0 # 1-Hit DMG|{param0:F1P}
    attack_2:
      - 1 # 2-Hit DMG|{param1:F1P}
    attack_3:
      - 2 # 3-Hit DMG|{param2:F1P}+{param3:F1P}
      - 3 # 3-Hit DMG|{param2:F1P}+{param3:F1P}
    attack_4:
      - 4 # 4-Hit DMG|{param4:F1P}
    charge:
      - 5 # Charged Attack DMG|{param5:F1P}
  skill: # Senet Strategy: Dance of a Thousand Nights
    nef_1_ATT:
      - 0 # Phantasm Performance Nefer 1|{param0:F1P} ATK+{param1:F1P} Elemental Mastery
    nef_1_EM:
      - 1 # Phantasm Performance Nefer 1|{param0:F1P} ATK+{param1:F1P} Elemental Mastery
    nef_2_ATT:
      - 2 # Phantasm Performance Nefer 2|{param2:F1P} ATK+{param3:F1P} Elemental Mastery
    nef_2_EM:
      - 3 # Phantasm Performance Nefer 2|{param2:F1P} ATK+{param3:F1P} Elemental Mastery
    shade_1:
      - 4 # Phantasm Performance Shade 1|{param4:F1P} Elemental Mastery
    shade_2:
      - 5 # Phantasm Performance Shade 2|{param5:F1P} Elemental Mastery
    shade_3:
      - 6 # Phantasm Performance Shade 3|{param6:F1P} Elemental Mastery
    nefer_c6_1:
      - 7 # Phantasm C6 Lunarbloom dmg 1|{param7:F1P} Elemental Mastery
    nefer_c6_2:
      - 7 # Phantasm C6 Lunarbloom AOE dmg 2|{param8:F1P} Elemental Mastery
  burst: # Sacred Vow: True Eye's Phantasm
    eye_1:
      - 0 # Sacred Vow 1 |{param0:F1P} ATK+{param1:F1P} Elemental Mastery
    eye_2:
      - 1 # Sacred Vow 2 |{param2:F1P} ATK+{param3:F1P} Elemental Mastery
documentation:
  fields_data:
    - fields: [.nefer.veil]
      desc: "Number of Falsehood stacks."
