id: 10000122
key: "nefer"
rarity: QUALITY_ORANGE
body: BODY_GIRL
region: ASSOC_TYPE_NODKRAI
element: Grass
weapon_class: WEAPON_CATALYST
icon_name: "UI_AvatarIcon_Nefer"
stats: { # TODO get decimal data for these fields
   base_hp: 959
   base_atk: 27
   base_def: 62
   base_em: 100
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 848
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 54
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 23
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 603
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 38
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 17
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.048
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 804
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 51
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 22
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.096
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 603
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 37
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 17
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.096
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 602
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 37
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 16
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.144
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 603
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 38
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 16
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.192
      }
   }
}
skill_details: {
   skill: 11222
   burst: 11225
   attack: 11221
   burst_energy_cost: 60
}
name_text_hash_map: 712501082
